import { Creator, Video, CommunityRequest, Requester } from '../types';

export const CREATORS: Creator[] = [
  {
    id: "Krypton T",
    name: "Krypton T",
    avatar: "https://cdn.qwenlm.ai/output/88ae44e3-1b93-4c51-8d6a-ae4d0dab9a46/t2i/ecc06355-1b93-4c51-8d6a-ae4d0dab9a46/cf079bc8-9280-48e5-b779-5cc7f6f8d3b0.png?key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXNvdXJjZV91c2VyX2lkIjoiODhhZTQ0ZTMtMWI5My00YzUxLThkNmEtYWU0ZDBhYjkyNjUiLCJyZXNvdXJjZV9pZCI6ImNmMDc5YmM4LTkyODAtNDhlNS03YzdmNmY4ZDNjOCIsImNyZWF0b3JfY2hhdF9pZCI6bnVsbH0.aU9y2SAvlNYxUYv0pfEyQhAtX-wIaqujKa7NPlL36Rs",
    bio: "A deep dive into alternative history scenarios, exploring pivotal moments and their potential ripple effects.",
    quote: '"History is not just what happened, but what could have been. Imagination fuels understanding."',
    isVerified: true,
    socialLinks: [
      { platform: "youtube", url: "https://youtube.com/kryptont" },
      { platform: "twitter", url: "https://twitter.com/kryptont" },
    ],
    portfolioUrl: "https://kryptont.com/portfolio",
    supportUrl: "https://patreon.com/kryptont",
    isAIenhanced: false,
    followers: 12000,
  },
  {
    id: "SpaceExplorer",
    name: "SpaceExplorer",
    avatar: "https://cdn.qwenlm.ai/output/88ae44e3-1b93-4c51-8d6a-ae4d0dab9a46/t2i/ecc06355-1b93-4c51-8d6a-ae4d0dab9a46/ee4f7acc-3d00-428f-90ed-2d96b65d94d4.png?key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXNvdXJjZV91c2VyX2lkIjoiODhhZTQ0ZTMtMWI5My00YzUxLThkNmEtYWU0ZDBhYjkyNjUiLCJyZXNvdXJjZV9pZCI6ImVlNGY3YWNjLTNkMDAtNDI4Zi05MGVkLTJkOTZiNjVkOTQ0NCIsImNyZWF0b3Jf2FjYXQtY2hhdF9pZCI6bnVsbH0.ySsAQAtUytOsP3EZQhCKCgSHwchGzEaCzkcURNrg5D54",
    bio: "Exploring the mysteries of space and human perception. Debunking myths with a scientific lens.",
    quote: '"The truth is out there, but so are the theories. Our mission is to find clarity."',
    isVerified: false,
    socialLinks: [
      { platform: "instagram", url: "https://instagram.com/spaceexplorer" },
    ],
    portfolioUrl: null,
    supportUrl: null,
    isAIenhanced: true,
    followers: 8500,
  },
  {
    id: "SociologyThinker",
    name: "SociologyThinker",
    avatar: "https://cdn.qwenlm.ai/output/88ae44e3-1b93-4c51-8d6a-ae4d0dab9a46/t2i/ecc06355-1b93-4c51-8d6a-ae4d0dab9a46/353a8478-0e21-4e3a-85c7-87442fb090ef.png?key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXNvdXJjZV91c2VyX2lkIjoiODhhZTQ0ZTMtMWI5My00YzUxLThkNmEtYWU0ZDBhYjkyNjUiLCJyZXNvdXJjZV9pZCI6IjM1M2E4NDc4LTBlMjEtNGUzYS04NWM3LTg3NDQyZmIwOTBlZiIsImNyZWF0b3JfY2hhdF9pZCI6bnVsbH0.-yErlq0KGsLbJUQO_zf-400ETC_LR6k-zw0WoTBfyelI",
    bio: "Analyzing societal structures and economic paradigms. Advocating for a more equitable future.",
    quote: '"Question everything, especially the status quo. Change begins with understanding."',
    isVerified: true,
    socialLinks: [
      { platform: "linkedin", url: "https://linkedin.com/sociologythinker" },
    ],
    portfolioUrl: null,
    supportUrl: "https://buymeacoffee.com/sociologythinker",
    isAIenhanced: false,
    followers: 25000,
  },
  {
    id: "MarketTruth",
    name: "MarketTruth",
    avatar: "https://sdmntprwestus.oaiusercontent.com/files/00000000-ecbc-6230-8d22-729c89e66988/raw?se=2025-05-22T06%3A27%3A35Z&sp=r&sv=2024-08-04&scid=5bd4a3ca-6af3-5b68-a1b1-70b03cbeaaf1&skoid=61180a4f-34a9-42b7-b76d-9ca47d89946d&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skt=2025-05-21T20%3A41%3A36Z&ske=2025-06-05T20%3A41%3A14Z&sks=b&skv=2024-08-04&sig=eLw7bUgGuWSUor/A9rzR4op7z/VpIk9zYdXE1CPqImQ%3D",
    bio: "Uncovering the hidden truths of financial markets, providing insights for informed decision-making.",
    quote: '"Knowledge is power, especially in the markets. Stay informed, stay ahead."',
    isVerified: false,
    socialLinks: [],
    portfolioUrl: null,
    supportUrl: null,
    isAIenhanced: true,
    followers: 6000,
  },
  {
    id: "AIInsights",
    name: "AIInsights",
    avatar: "https://placehold.co/40x40/101010/C4A77D?text=AI",
    bio: "Exploring the bleeding edge of artificial intelligence and its societal impact.",
    quote: "\"AI is not just about technology, it's about humanity's next chapter.\"",
    isVerified: true,
    socialLinks: [
      { platform: "twitter", url: "https://twitter.com/aiinsights" },
    ],
    portfolioUrl: "https://aiinsights.com",
    supportUrl: null,
    isAIenhanced: true,
    followers: 30000,
  },
  {
    id: "DesignTheory",
    name: "DesignTheory",
    avatar: "https://placehold.co/40x40/101010/C4A77D?text=DE",
    bio: "Simplifying complex design principles for aspiring creatives.",
    quote: '"Less is more, but clarity is everything."',
    isVerified: false,
    socialLinks: [
      { platform: "instagram", url: "https://instagram.com/designtory" },
    ],
    portfolioUrl: null,
    supportUrl: null,
    isAIenhanced: false,
    followers: 4500,
  },
  {
    id: "QuantumLeap",
    name: "QuantumLeap",
    avatar: "https://placehold.co/40x40/101010/C4A77D?text=QL",
    bio: "Demystifying complex physics concepts for the curious mind.",
    quote: '"The universe is stranger than we can imagine."',
    isVerified: true,
    socialLinks: [
      { platform: "twitter", url: "https://twitter.com/quantumleap" },
    ],
    portfolioUrl: null,
    supportUrl: null,
    isAIenhanced: false,
    followers: 9000,
  },
  {
    id: "CosmicVoyager",
    name: "CosmicVoyager",
    avatar: "https://placehold.co/40x40/101010/C4A77D?text=CV",
    bio: "Exploring the unseen forces that shape our universe.",
    quote: '"The cosmos holds more secrets than stars."',
    isVerified: false,
    socialLinks: [],
    portfolioUrl: null,
    supportUrl: null,
    isAIenhanced: true,
    followers: 7200,
  },
];

export const VIDEOS: Video[] = [
  {
    id: "1",
    title: "What if the Cold War went hot? An Alternate History",
    creator: "Krypton T",
    time: "1 month ago",
    requestedBy: "OceanDreamer",
    thumbnail: "https://cdn.qwenlm.ai/output/88ae44e3-1b93-4c51-8d6a-ae4d0dab9a46/t2i/ecc06355-9de3-4f19-bf1d-1524fa1cb984/cf079bc8-9280-48e5-b779-5cc7f6f8d3b0.png?key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXNvdXJjZV91c2VyX2lkIjoiODhhZTQ0ZTMtMWI5My00YzUxLThkNmEtYWU0ZDBhYjkyNjUiLCJyZXNvdXJjZV9pZCI6ImNmMDc5YmM4LTkyODAtNDhlNS03YzdmNmY4ZDNjOCIsImNyZWF0b3JfY2hhdF9pZCI6bnVsbH0.aU9y2SAvlNYxUYv0pfEyQhAtX-wIaqujKa7NPlL36Rs",
    duration: "4:30",
    requested: true,
    isAIenhanced: false,
  },
  {
    id: "2",
    title: "Why Was the Moon Landing Conspiracy So Believable?",
    creator: "SpaceExplorer",
    time: "2 weeks ago",
    requestedBy: "HistoryJunkie",
    thumbnail: "https://cdn.qwenlm.ai/output/88ae44e3-1b93-4c51-8d6a-ae4d0dab9a46/t2i/ecc06355-9de3-4f19-bf1d-1524fa1cb984/ee4f7acc-3d00-428f-90ed-2d96b65d94d4.png?key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXNvdXJjZV91c2VyX2lkIjoiODhhZTQ0ZTMtMWI5My00YzUxLThkNmEtYWU0ZDBhYjkyNjUiLCJyZXNvdXJjZV9pZCI6ImVlNGY3YWNjLTNkMDAtNDI4Zi05MGVkLTJkOTZiNjVkOTQ0NCIsImNyZWF0b3Jf2FjYXQtY2hhdF9pZCI6bnVsbH0.ySsAQAtUytOsP3EZQhCKCgSHwchGzEaCzkcURNrg5D54",
    duration: "5:30",
    requested: false,
    isAIenhanced: true,
  },
  {
    id: "3",
    title: "Are We All Just Working to Make Billionaires Richer?",
    creator: "SociologyThinker",
    time: "1 week ago",
    requestedBy: "SocialRevolutionary",
    thumbnail: "https://cdn.qwenlm.ai/output/88ae44e3-1b93-4c51-8d6a-ae4d0dab9a46/t2i/ecc06355-1b93-4c51-8d6a-ae4d0dab9a46/353a8478-0e21-4e3a-85c7-87442fb090ef.png?key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXNvdXJjZV91c2VyX2lkIjoiODhhZTQ0ZTMtMWI5My00YzUxLThkNmEtYWU0ZDBhYjkyNjUiLCJyZXNvdXJjZV9pZCI6IjM1M2E4NDc4LTBlMjEtNGUzYS04NWM3LTg3NDQyZmIwOTBlZiIsImNyZWF0b3JfY2hhdF9pZCI6bnVsbH0.-yErlq0KGsLbJUQO_zf-400ETC_LR6k-zw0WoTBfyelI",
    duration: "5:00",
    requested: false,
    isAIenhanced: false,
  },
  {
    id: "4",
    title: "Is the Stock Market Rigged to Keep Average People from Getting Rich?",
    creator: "MarketTruth",
    time: "1 week ago",
    requestedBy: "EconomicSleuth",
    thumbnail: "https://sdmntprwestus.oaiusercontent.com/files/00000000-ecbc-6230-8d22-729c89e66988/raw?se=2025-05-22T06%3A27%3A35Z&sp=r&sv=2024-08-04&scid=5bd4a3ca-6af3-5b68-a1b1-70b03cbeaaf1&skoid=61180a4f-34a9-42b7-b76d-9ca47d89946d&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skt=2025-05-21T20%3A41%3A36Z&ske=2025-06-05T20%3A41%3A14Z&sks=b&skv=2024-08-04&sig=eLw7bUgGuWSUor/A9rzR4op7z/VpIk9zYdXE1CPqImQ%3D",
    duration: "5:25",
    requested: false,
    isAIenhanced: true,
  },
  {
    id: "5",
    title: "The Future of AI: From Chatbots to Consciousness",
    creator: "AIInsights",
    time: "3 days ago",
    requestedBy: "TechFuturist",
    thumbnail: "https://placehold.co/400x220/1A1A1A/C4A77D?text=AI+Future",
    duration: "7:10",
    requested: true,
    isAIenhanced: true,
  },
  {
    id: "6",
    title: "Mastering Minimalist Design: A Guide for Beginners",
    creator: "DesignTheory",
    time: "2 months ago",
    requestedBy: "DesignLover",
    thumbnail: "https://placehold.co/400x220/101010/C4A77D?text=Minimal+Design",
    duration: "8:45",
    requested: false,
    isAIenhanced: false,
  },
  {
    id: "7",
    title: "Understanding Quantum Computing Basics",
    creator: "QuantumLeap",
    time: "1 week ago",
    requestedBy: "OceanDreamer",
    thumbnail: "https://placehold.co/400x220/1A1A1A/C4A77D?text=Quantum+Comp",
    duration: "6:00",
    requested: true,
    isAIenhanced: false,
  },
  {
    id: "8",
    title: "The Enigma of Dark Matter and Dark Energy",
    creator: "CosmicVoyager",
    time: "2 days ago",
    requestedBy: "OceanDreamer",
    thumbnail: "https://placehold.co/400x220/1A1A1A/C4A77D?text=Dark+Matter",
    duration: "7:30",
    requested: true,
    isAIenhanced: true,
  },
];

export const COMMUNITY_REQUESTS: CommunityRequest[] = [
  {
    id: "cr1",
    user: {
      name: "CryptoGuru",
      avatar: "https://placehold.co/40x40/101010/C4A77D?text=CG",
    },
    timestamp: "Requested 3 days ago",
    tags: ["#blockchain", "#finance"],
    title: "Decentralized Finance Explained for Dummies",
    description: "A beginner-friendly video breaking down complex DeFi concepts into understandable terms, focusing on real-world examples and potential risks.",
    attachments: [
      {
        type: "image",
        uri: "https://placehold.co/200x120/101010/C4A77D?text=DeFi+Concept",
      },
    ],
    upvotes: 125,
    comments: 42,
    boosts: 15,
    tips: 50,
    isBookmarked: false,
    visibility: "Public",
    recentBoosters: [
      { avatar: "https://placehold.co/20x20/101010/CCCCCC?text=U1" },
      { avatar: "https://placehold.co/20x20/101010/CCCCCC?text=U2" },
      { avatar: "https://placehold.co/20x20/101010/CCCCCC?text=U3" },
    ],
  },
  {
    id: "cr2",
    user: {
      name: "ArtLover22",
      avatar: "https://placehold.co/40x40/101010/C4A77D?text=AL",
    },
    timestamp: "Requested 1 week ago",
    tags: ["#art", "#history"],
    title: "The Hidden Meanings in Renaissance Paintings",
    description: "Explore the symbolism and secret messages embedded in famous Renaissance masterpieces.",
    attachments: [
      {
        type: "image",
        uri: "https://placehold.co/200x120/101010/C4A77D?text=Renaissance+Art",
      },
    ],
    upvotes: 80,
    comments: 20,
    boosts: 5,
    tips: 10,
    isBookmarked: true,
    visibility: "Public",
    recentBoosters: [
      { avatar: "https://placehold.co/20x20/101010/CCCCCC?text=U4" },
    ],
  },
  {
    id: "cr3",
    user: {
      name: "EcoWarrior",
      avatar: "https://placehold.co/40x40/101010/C4A77D?text=EW",
    },
    timestamp: "Requested 2 days ago",
    tags: ["#environment", "#sustainability"],
    title: "Sustainable Living: A Practical Guide",
    description: "Practical tips and actionable steps for adopting a more sustainable lifestyle, from reducing waste to conserving energy.",
    attachments: [],
    upvotes: 210,
    comments: 65,
    boosts: 20,
    tips: 75,
    isBookmarked: false,
    visibility: "Sponsored Opportunity",
    recentBoosters: [
      { avatar: "https://placehold.co/20x20/101010/CCCCCC?text=U5" },
      { avatar: "https://placehold.co/20x20/101010/CCCCCC?text=U6" },
      { avatar: "https://placehold.co/20x20/101010/CCCCCC?text=U7" },
    ],
  },
  {
    id: "cr4",
    user: {
      name: "TechGeek",
      avatar: "https://placehold.co/40x40/101010/C4A77D?text=TG",
    },
    timestamp: "Requested 4 days ago",
    tags: ["#AI", "#futuretech"],
    title: "The Ethics of Artificial Intelligence",
    description: "A thoughtful discussion on the moral and societal implications of rapidly advancing AI technologies.",
    attachments: [],
    upvotes: 95,
    comments: 30,
    boosts: 8,
    tips: 25,
    isBookmarked: false,
    visibility: "Public",
    recentBoosters: [],
  },
  {
    id: "cr5",
    user: {
      name: "FoodieFan",
      avatar: "https://placehold.co/40x40/101010/C4A77D?text=FF",
    },
    timestamp: "Requested 5 days ago",
    tags: ["#cooking", "#globalcuisine"],
    title: "Mastering Authentic Street Food Recipes",
    description: "Learn to cook delicious and authentic street food from around the world with easy-to-follow recipes.",
    attachments: [
      {
        type: "image",
        uri: "https://placehold.co/200x120/101010/C4A77D?text=Street+Food",
      },
    ],
    upvotes: 180,
    comments: 50,
    boosts: 10,
    tips: 60,
    isBookmarked: false,
    visibility: "Public",
    recentBoosters: [
      { avatar: "https://placehold.co/20x20/101010/CCCCCC?text=U8" },
      { avatar: "https://placehold.co/20x20/101010/CCCCCC?text=U9" },
    ],
  },
];

export const REQUESTERS: Requester[] = [
  {
    id: "OceanDreamer",
    name: "OceanDreamer",
    isTopRequestor: true,
    avatar: "https://placehold.co/40x40/101010/C4A77D?text=OD",
    bio: "Curious about lost civilizations. Requesting videos that challenge conventional history.",
    requestPhilosophy: "Driven by a desire to explore the unknown and uncover hidden truths. I believe in the power of visual storytelling to educate and inspire.",
    requestLevel: "Dream Architect",
    joinedDate: "May 2024",
    totalRequests: 15,
    completedRequests: 10,
    mostLikedRequest: {
      title: "Ancient Alien Theories Unveiled",
      thumbnail: "https://sdmntprwestus2.oaiusercontent.com/files/00000000-ee6c-61f8-8cc2-dc7aed06ee48/raw?se=2025-05-22T06%3A43%3A10Z&sp=r&sv=2024-08-04&scid=f3c306ff-6759-55e3-a490-09cc77bcdc70&skoid=1e6af1bf-6b08-4a04-8919-15773e7e7024&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skt=2025-05-22T05%3A40%3A14Z&ske=2025-06-05T05%3A40%3A14Z&sks=b&skv=2024-08-04&sig=eLw7bUgGuWSUor/A9rzR4op7z/VpIk9zYdXE1CPqImQ%3D",
      upvotes: 250,
    },
    requestCategories: ["History 📜", "Mystery 🔍", "Speculative Fiction 👽"],
    publicProfileLink: "https://oceandreamer.com/profile",
    socialHandles: {
      twitter: "@OceanDreamer_X",
      discord: "Ocean#1234",
    },
    communityThankYous: 8,
    isSupporter: true,
    donatedAmount: 23,
    requestedVideos: ["1", "7", "8"],
  },
  {
    id: "HistoryJunkie",
    name: "HistoryJunkie",
    isTopRequestor: false,
    avatar: "https://placehold.co/40x40/101010/C4A77D?text=HJ",
    bio: "Fascinated by forgotten stories and pivotal moments.",
    requestPhilosophy: "I enjoy diving deep into historical events and uncovering their true impact. My requests focus on shedding light on untold narratives.",
    requestLevel: "Visionary",
    joinedDate: "Jan 2024",
    totalRequests: 7,
    completedRequests: 5,
    mostLikedRequest: {
      title: "The Rise and Fall of Ancient Rome",
      thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTuyrOMSy7Qbo09OUFvGOd8lZr57bDYuLMpxw&s",
      upvotes: 180,
    },
    requestCategories: ["History 📜", "Politics 🏛️"],
    publicProfileLink: null,
    socialHandles: {
      instagram: "@history_junkie_official",
    },
    communityThankYous: 3,
    isSupporter: false,
    donatedAmount: 0,
    requestedVideos: [],
  },
  {
    id: "SocialRevolutionary",
    name: "SocialRevolutionary",
    isTopRequestor: false,
    avatar: "https://placehold.co/40x40/101010/C4A77D?text=SR",
    bio: "Advocating for systemic change through educational content.",
    requestPhilosophy: "My goal is to spark critical thinking and encourage action towards a more equitable society. I seek content that challenges the status quo.",
    requestLevel: "Power Requestor",
    joinedDate: "Feb 2025",
    totalRequests: 20,
    completedRequests: 18,
    mostLikedRequest: {
      title: "Rethinking Capitalism: A Modern Critique",
      thumbnail: "https://sdmntprcentralus.oaiusercontent.com/files/00000000-3d88-61f5-a277-aafc460e865a/raw?se=2025-06-04T15%3A02%3A35Z&sp=r&sv=2024-08-04&scid=22736c51-ff2c-5be4-9df8-f12873f023ca&skoid=5cab1ff4-c20d-41dc-babb-df0c2cc21dd4&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skt=2025-06-04T13%3A00%3A18Z&ske=2025-06-05T13%3A00%3A18Z&sks=b&skv=2024-08-04&sig=pJ9XpqrQG8zfTIjpjaktyJaRbkyJaRbky3rv2QjTe8PsTWE4%3D",
      upvotes: 310,
    },
    requestCategories: ["Sociology ⚖️", "Economics 💹", "Philosophy 🧠"],
    publicProfileLink: null,
    socialHandles: {
      youtube: "SocialRevolutionaryTube",
    },
    communityThankYous: 12,
    isSupporter: true,
    donatedAmount: 75,
    requestedVideos: [],
  },
  {
    id: "EconomicSleuth",
    name: "EconomicSleuth",
    isTopRequestor: true,
    avatar: "https://placehold.co/40x40/101010/C4A77D?text=ES",
    bio: "Unraveling the complexities of global finance.",
    requestPhilosophy: "I thrive on understanding the intricate workings of financial systems and exposing biases or hidden truths. My requests aim to demystify complex economic topics.",
    requestLevel: "Dream Architect",
    joinedDate: "March 2025",
    totalRequests: 10,
    completedRequests: 8,
    mostLikedRequest: {
      title: "Inside the Shadow Economy",
      thumbnail: "https://sdmntprwestus.oaiusercontent.com/files/00000000-ecbc-6230-8d22-729c89e66988/raw?se=2025-05-22T06%3A27%3A35Z&sp=r&sv=2024-08-04&scid=5bd4a3ca-6af3-5b68-a1b1-70b03cbeaaf1&skoid=61180a4f-34a9-42b7-b76d-9ca47d89946d&sktid=a48cca56-e6da-484e-a814-9c849652bcb3&skt=2025-05-21T20%3A41%3A36Z&ske=2025-06-05T20%3A41%3A14Z&sks=b&skv=2024-08-04&sig=eLw7bUgGuWSUor/A9rzR4op7z/VpIk9zYdXE1CPqImQ%3D",
      upvotes: 195,
    },
    requestCategories: ["Economics 💹", "Investigative 🕵️", "Finance 💰"],
    publicProfileLink: null,
    socialHandles: {
      twitter: "@EconomicSleuth",
    },
    communityThankYous: 6,
    isSupporter: true,
    donatedAmount: 40,
    requestedVideos: [],
  },
  {
    id: "TechFuturist",
    name: "TechFuturist",
    isTopRequestor: false,
    avatar: "https://placehold.co/40x40/101010/C4A77D?text=TF",
    bio: "Pioneering thought in future technologies and their implications.",
    requestPhilosophy: "I believe understanding tomorrow starts with questioning today. I seek content that pushes boundaries and envisions new possibilities.",
    requestLevel: "Visionary",
    joinedDate: "May 2025",
    totalRequests: 3,
    completedRequests: 2,
    mostLikedRequest: null,
    requestCategories: ["AI 🤖", "Future Tech 🚀", "Philosophy 🧠"],
    publicProfileLink: null,
    socialHandles: { twitter: "@TechFuturistAI" },
    communityThankYous: 1,
    isSupporter: false,
    donatedAmount: 0,
    requestedVideos: ["5"],
  },
  {
    id: "DesignLover",
    name: "DesignLover",
    isTopRequestor: false,
    avatar: "https://placehold.co/40x40/101010/C4A77D?text=DL",
    bio: "Appreciating and advocating for beautiful, functional design.",
    requestPhilosophy: "Good design simplifies life. I request content that educates and inspires designers of all levels.",
    requestLevel: "Newbie",
    joinedDate: "June 2025",
    totalRequests: 1,
    completedRequests: 1,
    mostLikedRequest: null,
    requestCategories: ["Design 🎨", "Tutorials 📚"],
    publicProfileLink: null,
    socialHandles: {},
    communityThankYous: 0,
    isSupporter: false,
    donatedAmount: 0,
    requestedVideos: ["6"],
  },
];