import { StyleSheet } from 'react-native';
import { COLORS } from '../utils/colors';

export const videoCardStyles = StyleSheet.create({
  card: {
    backgroundColor: COLORS.cardBackground,
    borderRadius: 20,
    marginHorizontal: 18,
    marginBottom: 35,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    overflow: "hidden",
    shadowColor: COLORS.shadowColor,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.25,
    shadowRadius: 15,
    elevation: 12,
  },
  thumbContainer: {
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    overflow: "hidden",
    position: "relative",
  },
  thumbnail: {
    width: "100%",
    height: 200,
  },
  thumbnailPlaceholder: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: COLORS.cardBackground,
    justifyContent: "center",
    alignItems: "center",
  },
  imageFog: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    height: 70,
  },
  badge: {
    position: "absolute",
    top: 15,
    right: 15,
    backgroundColor: COLORS.primaryAccent,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 10,
    flexDirection: "row",
    alignItems: "center",
    shadowColor: COLORS.primaryAccent,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 10,
    elevation: 8,
  },
  badgeIcon: {
    marginRight: 6,
  },
  badgeText: {
    color: COLORS.cardBackground,
    fontSize: 12,
    fontWeight: "bold",
    fontFamily: "Segoe UI Semilight",
  },
  duration: {
    position: "absolute",
    bottom: 15,
    right: 15,
    backgroundColor: "rgba(0,0,0,0.7)",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  durationText: {
    color: COLORS.textWhite,
    fontSize: 11,
    fontFamily: "Segoe UI Semilight",
  },
  info: { padding: 20 },
  title: {
    color: COLORS.textWhite,
    fontSize: 17,
    fontFamily: "Segoe UI Semilight",
    fontWeight: "600",
    marginBottom: 8,
    lineHeight: 24,
  },
  creator: {
    color: COLORS.textLightGray,
    fontSize: 13,
    fontFamily: "Segoe UI Semilight",
    marginBottom: 5,
    flexDirection: "row",
    alignItems: "center",
  },
  creatorName: {
    textDecorationLine: "underline",
    color: COLORS.secondaryAccent,
    fontWeight: "bold",
    textDecorationColor: COLORS.secondaryAccent,
  },
  requesterNameLink: {
    textDecorationLine: "underline",
    color: COLORS.primaryAccent,
    fontWeight: "bold",
    textDecorationColor: COLORS.primaryAccent,
  },
  metaRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 5,
  },
  metaText: {
    color: COLORS.textMediumGray,
    fontSize: 11,
    fontFamily: "Segoe UI Semilight",
  },
  moreIconWrapper: {
    padding: 10,
    marginRight: -10,
  },
});

export const communityCardStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
    paddingTop: 15,
  },
  stickyHeader: {
    backgroundColor: COLORS.background,
    paddingHorizontal: 18,
    paddingBottom: 20,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: COLORS.buttonBorder,
    zIndex: 1,
  },
  communitySearchInput: {
    backgroundColor: COLORS.cardBackground,
    borderRadius: 15,
    paddingHorizontal: 18,
    paddingVertical: 12,
    color: COLORS.textWhite,
    fontSize: 15,
    fontFamily: "Segoe UI Semilight",
    marginBottom: 15,
    shadowColor: COLORS.shadowColor,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 8,
    borderWidth: 1,
    borderColor: COLORS.buttonBorder,
  },
  chipScrollViewContent: {
    paddingRight: 20,
  },
  filterChip: {
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.08)",
    borderRadius: 15,
    paddingVertical: 10,
    paddingHorizontal: 15,
    marginRight: 10,
    marginTop: 8,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: COLORS.buttonBorder,
    width: 85,
    height: 75,
  },
  filterChipSelected: {
    backgroundColor: COLORS.primaryAccent,
    borderColor: COLORS.secondaryAccent,
  },
  chipIcon: {
    marginBottom: 5,
  },
  filterChipText: {
    color: COLORS.textLightGray,
    fontSize: 11,
    fontWeight: "500",
    fontFamily: "Segoe UI Semilight",
    textAlign: "center",
  },
  filterChipTextSelected: {
    color: COLORS.cardBackground,
    fontWeight: "bold",
  },
  dropdownWrapper: {
    marginRight: 10,
    marginTop: 8,
    marginBottom: 8,
  },
  emptyStateContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 30,
    minHeight: 250,
  },
  emptyStateText: {
    color: COLORS.textLightGray,
    fontSize: 18,
    fontWeight: "600",
    textAlign: "center",
    marginBottom: 12,
    fontFamily: "Segoe UI Semilight",
  },
  emptyStateSubText: {
    color: COLORS.textMediumGray,
    fontSize: 14,
    textAlign: "center",
    fontFamily: "Segoe UI Semilight",
  },
  cardGridContainer: {
    paddingHorizontal: 15,
    paddingTop: 15,
    paddingBottom: 120,
  },
  card: {
    backgroundColor: COLORS.cardBackground,
    borderRadius: 20,
    margin: 8,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    overflow: "hidden",
    flex: 1,
    shadowColor: COLORS.shadowColor,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.25,
    shadowRadius: 15,
    elevation: 12,
  },
  cardHeader: {
    flexDirection: "row",
    alignItems: "center",
    padding: 15,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: COLORS.buttonBorder,
  },
  userAvatar: {
    width: 38,
    height: 38,
    borderRadius: 10,
    marginRight: 12,
    borderWidth: 1.5,
    borderColor: COLORS.primaryAccent,
  },
  userInfo: {
    flex: 1,
  },
  username: {
    color: COLORS.textWhite,
    fontSize: 13,
    fontWeight: "600",
    fontFamily: "Segoe UI Semilight",
  },
  timestamp: {
    color: COLORS.textMediumGray,
    fontSize: 10,
    fontFamily: "Segoe UI Semilight",
  },
  tagBadge: {
    backgroundColor: "rgba(255,255,255,0.1)",
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  tagText: {
    color: COLORS.textLightGray,
    fontSize: 11,
    fontWeight: "bold",
    fontFamily: "Segoe UI Semilight",
  },
  cardBody: {
    padding: 15,
  },
  cardTitle: {
    color: COLORS.textWhite,
    fontSize: 15,
    fontWeight: "bold",
    marginBottom: 8,
    fontFamily: "Segoe UI Semilight",
    lineHeight: 20,
  },
  cardDescription: {
    color: COLORS.textLightGray,
    fontSize: 12,
    lineHeight: 18,
    marginBottom: 12,
    fontFamily: "Segoe UI Semilight",
  },
  attachedImagePlaceholder: {
    backgroundColor: COLORS.background,
    justifyContent: "center",
    alignItems: "center",
    height: 120,
    borderRadius: 10,
    marginBottom: 12,
  },
  attachedImage: {
    width: "100%",
    height: 120,
    borderRadius: 10,
    marginBottom: 12,
  },
  sponsoredBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.secondaryAccent,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 5,
    alignSelf: "flex-start",
    marginTop: 8,
    shadowColor: COLORS.secondaryAccent,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 10,
    elevation: 8,
  },
  sponsoredText: {
    color: COLORS.cardBackground,
    fontSize: 11,
    fontWeight: "bold",
    marginLeft: 6,
    fontFamily: "Segoe UI Semilight",
  },
  interactionRow: {
    flexDirection: "row",
    justifyContent: "space-around",
    paddingVertical: 12,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: COLORS.buttonBorder,
  },
  interactionButton: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 10,
  },
  interactionCount: {
    color: COLORS.textLightGray,
    fontSize: 12,
    marginLeft: 6,
    fontFamily: "Segoe UI Semilight",
  },
  floatingCTA: {
    position: "absolute",
    bottom: 40,
    right: 30,
    zIndex: 10,
    flexDirection: "column",
    alignItems: "flex-end",
  },
  hintContainer: {
    marginBottom: 15,
    alignItems: "flex-end",
  },
  hintBlurBackground: {
    borderRadius: 15,
    overflow: "hidden",
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderColor: "rgba(255,255,255,0.2)",
    borderWidth: 1,
  },
  hintText: {
    color: COLORS.textWhite,
    fontSize: 14,
    fontFamily: "Segoe UI Semilight",
    textAlign: "right",
    lineHeight: 20,
  },
  hintArrowContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 5,
  },
  hintArrow: {
    marginLeft: 8,
  },
  floatingCTAButton: {
    width: 55,
    height: 55,
    backgroundColor: COLORS.primaryAccent,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: COLORS.primaryAccent,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.6,
    shadowRadius: 20,
    elevation: 15,
  },
});