import { StyleSheet, Platform, StatusBar } from 'react-native';
import { COLORS } from '../utils/colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
    paddingTop: Platform.OS === "android" ? StatusBar.currentHeight + 15 : 0,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    height: 44,
    backgroundColor: COLORS.cardBackground,
    borderRadius: 12,
    marginHorizontal: 18,
    marginBottom: 25,
    paddingHorizontal: 16,
    shadowColor: COLORS.shadowColor,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 8,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: COLORS.buttonBorder,
  },
  iconSpacing: { marginHorizontal: 8 },
  searchIconContainer: {
    padding: 8,
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
    marginLeft: "auto",
    marginRight: 10,
  },
  searchBarExpanded: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
    backgroundColor: "rgba(255,255,255,0.05)",
    borderRadius: 10,
    paddingHorizontal: 10,
    height: "80%",
  },
  searchInputExpanded: {
    flex: 1,
    color: COLORS.textWhite,
    fontSize: 15,
    fontFamily: "Segoe UI Semilight",
    paddingVertical: 0,
    paddingRight: 5,
  },
  searchBarCloseIcon: {
    padding: 5,
  },
  filterButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.05)",
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
    marginLeft: 10,
    borderWidth: 1,
    borderColor: COLORS.buttonBorder,
  },
  filterButtonText: {
    color: COLORS.primaryAccent,
    fontSize: 14,
    fontFamily: "Segoe UI Semilight",
    fontWeight: "600",
    marginRight: 6,
  },
  filterButtonIcon: {
    color: COLORS.primaryAccent,
  },
  flatListStyle: {
    flex: 1,
  },
  bottomNav: {
    backgroundColor: COLORS.background,
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    borderTopColor: COLORS.buttonBorder,
    borderTopWidth: StyleSheet.hairlineWidth,
    paddingVertical: 18,
    paddingHorizontal: 15,
    paddingBottom: Platform.OS === "android" ? 60 : 0,
    shadowColor: COLORS.shadowColor,
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.2,
    shadowRadius: 10,
    elevation: 10,
  },
  navButtonWrapper: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 15,
    overflow: "hidden",
    justifyContent: "center",
    alignItems: "center",
  },
  navItemSeparator: {
    width: StyleSheet.hairlineWidth,
    height: 28,
    backgroundColor: COLORS.buttonBorder,
    marginHorizontal: 10,
  },
  filterBar: {
    flexDirection: "row",
    justifyContent: "space-around",
    marginHorizontal: 18,
    marginBottom: 25,
    backgroundColor: COLORS.cardBackground,
    borderRadius: 15,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: COLORS.buttonBorder,
    shadowColor: COLORS.shadowColor,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 5,
  },
  filterOption: {
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 12,
  },
  filterOptionSelected: {
    borderBottomWidth: 2,
    borderBottomColor: COLORS.primaryAccent,
    paddingBottom: 8,
  },
  filterText: {
    color: COLORS.textLightGray,
    fontSize: 13,
    fontFamily: "Segoe UI Semilight",
    fontWeight: "400",
  },
  filterTextSelected: {
    fontWeight: "600",
    color: COLORS.primaryAccent,
  },
  emptyStateContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 30,
    minHeight: 250,
  },
  emptyStateText: {
    color: COLORS.textLightGray,
    fontSize: 18,
    fontWeight: "600",
    textAlign: "center",
    marginBottom: 12,
    fontFamily: "Segoe UI Semilight",
  },
  emptyStateSubText: {
    color: COLORS.textMediumGray,
    fontSize: 14,
    textAlign: "center",
    fontFamily: "Segoe UI Semilight",
  },
});