import { StyleSheet, Platform } from 'react-native';
import { COLORS } from '../utils/colors';

export const modalStyles = StyleSheet.create({
  centeredView: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.75)",
  },
  modalBlur: {
    borderRadius: 25,
    overflow: "hidden",
    width: "90%",
    maxWidth: 480,
    shadowColor: COLORS.shadowColor,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 18,
    elevation: 15,
  },
  modalContent: {
    backgroundColor: COLORS.cardBackground,
    borderRadius: 25,
    padding: 30,
    alignItems: "center",
    borderWidth: 1,
    borderColor: COLORS.buttonBorder,
  },
  closeButton: {
    position: "absolute",
    top: 18,
    right: 18,
    padding: 8,
    zIndex: 1,
  },
  modalTitle: {
    color: COLORS.textWhite,
    fontSize: 20,
    fontWeight: "bold",
    marginBottom: 15,
    fontFamily: "Segoe UI Semilight",
  },
  modalSubtitle: {
    color: COLORS.textLightGray,
    fontSize: 16,
    textAlign: "center",
    marginBottom: 25,
    fontFamily: "Segoe UI Semilight",
    lineHeight: 22,
  },
  inputGroup: {
    marginBottom: 25,
    width: "100%",
  },
  inputLabel: {
    color: COLORS.textLightGray,
    fontSize: 16,
    fontWeight: "600",
    marginBottom: 10,
    fontFamily: "Segoe UI Semilight",
  },
  textInput: {
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    color: COLORS.textWhite,
    fontSize: 16,
    padding: 15,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.buttonBorder,
    fontFamily: "Segoe UI Semilight",
    minHeight: 50,
  },
  textArea: {
    minHeight: 100,
    textAlignVertical: "top",
  },
  modalActions: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    marginTop: 20,
  },
  cancelButton: {
    flex: 1,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    paddingVertical: 15,
    borderRadius: 12,
    marginRight: 10,
    alignItems: "center",
    borderWidth: 1,
    borderColor: COLORS.buttonBorder,
  },
  cancelButtonText: {
    color: COLORS.textLightGray,
    fontSize: 16,
    fontWeight: "600",
    fontFamily: "Segoe UI Semilight",
  },
  submitButton: {
    flex: 1,
    backgroundColor: COLORS.primaryAccent,
    paddingVertical: 15,
    borderRadius: 12,
    marginLeft: 10,
    alignItems: "center",
    shadowColor: COLORS.primaryAccent,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  submitButtonDisabled: {
    backgroundColor: COLORS.textMediumGray,
    shadowOpacity: 0,
  },
  submitButtonText: {
    color: COLORS.cardBackground,
    fontSize: 16,
    fontWeight: "bold",
    fontFamily: "Segoe UI Semilight",
  },
  submitButtonTextDisabled: {
    color: COLORS.textLightGray,
  },
  // Report Modal specific styles
  reasonsList: {
    width: "100%",
    maxHeight: 300,
  },
  reasonItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 15,
    paddingHorizontal: 20,
    borderRadius: 12,
    marginBottom: 10,
    backgroundColor: "rgba(255, 255, 255, 0.03)",
    borderWidth: 1,
    borderColor: COLORS.buttonBorder,
  },
  reasonItemSelected: {
    backgroundColor: "rgba(196, 167, 125, 0.1)",
    borderColor: COLORS.primaryAccent,
  },
  reasonIcon: {
    marginRight: 15,
    width: 20,
  },
  reasonText: {
    color: COLORS.textLightGray,
    fontSize: 16,
    fontFamily: "Segoe UI Semilight",
    flex: 1,
  },
  reasonTextSelected: {
    color: COLORS.textWhite,
    fontWeight: "600",
  },
});

export const contextMenuStyles = StyleSheet.create({
  overlay: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.75)",
  },
  overlayTouchArea: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  menuContainer: {
    backgroundColor: COLORS.cardBackground,
    borderRadius: 15,
    paddingVertical: 8,
    shadowColor: COLORS.shadowColor,
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 10,
    width: "75%",
    maxWidth: 280,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: COLORS.buttonBorder,
    zIndex: 1000,
  },
  menuItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: COLORS.buttonBorder,
  },
  menuItemLast: {
    borderBottomWidth: 0,
  },
  menuItemIcon: {
    marginRight: 15,
    width: 20,
  },
  menuItemText: {
    color: COLORS.textWhite,
    fontSize: 16,
    fontFamily: "Segoe UI Semilight",
    fontWeight: "500",
    flex: 1,
  },
  reportText: {
    color: COLORS.secondaryAccent,
  },
});

export const profileModalStyles = StyleSheet.create({
  centeredView: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.75)",
  },
  modalBlur: {
    borderRadius: 25,
    overflow: "hidden",
    width: "90%",
    maxWidth: 380,
    maxHeight: "85%",
    shadowColor: COLORS.shadowColor,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.4,
    shadowRadius: 20,
    elevation: 15,
  },
  flipCardContainer: {
    width: "100%",
    height: "100%",
    position: "relative",
  },
  flipCard: {
    width: "100%",
    height: "100%",
    backfaceVisibility: "hidden",
    position: "absolute",
    top: 0,
    left: 0,
  },
  flipCardFront: {
    zIndex: 2,
  },
  flipCardBack: {
    transform: [{ rotateY: "180deg" }],
    zIndex: 1,
  },
  modalView: {
    backgroundColor: COLORS.cardBackground,
    borderRadius: 25,
    paddingHorizontal: 25,
    paddingVertical: 35,
    alignItems: "center",
    borderWidth: 1,
    borderColor: COLORS.buttonBorder,
    width: "100%",
    position: "relative",
  },
  closeButton: {
    position: "absolute",
    top: 18,
    right: 18,
    padding: 8,
    zIndex: 3,
  },
  goldBorder: {
    borderWidth: 2,
    borderColor: COLORS.primaryAccent,
  },
  topShapeContainer: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 100,
    overflow: "hidden",
    borderTopLeftRadius: 25,
    borderTopRightRadius: 25,
    alignItems: "center",
  },
  topShapeMain: {
    position: "absolute",
    top: -50,
    width: "120%",
    height: 180,
    borderRadius: 90,
    backgroundColor: COLORS.primaryAccent,
    opacity: 0.2,
  },
  topShapeAccent: {
    position: "absolute",
    top: -60,
    width: "100%",
    height: 150,
    borderRadius: 75,
    backgroundColor: COLORS.secondaryAccent,
    opacity: 0.1,
    transform: [{ rotate: "15deg" }],
  },
  profileAvatar: {
    width: 100,
    height: 100,
    borderRadius: 50,
    marginBottom: 15,
    marginTop: 20,
    zIndex: 2,
    borderWidth: 3,
    borderColor: COLORS.primaryAccent,
    shadowColor: COLORS.primaryAccent,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.5,
    shadowRadius: 10,
  },
  profileName: {
    color: COLORS.textWhite,
    fontSize: 24,
    fontWeight: "bold",
    fontFamily: "Segoe UI Semilight",
    marginBottom: 5,
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  profileRole: {
    color: COLORS.secondaryAccent,
    fontSize: 16,
    fontWeight: "600",
    fontFamily: "Segoe UI Semilight",
    marginBottom: 5,
  },
  verifiedBadge: {
    marginTop: 5,
    marginBottom: 15,
  },
  statsContainer: {
    flexDirection: "row",
    width: "90%",
    justifyContent: "space-around",
    marginBottom: 25,
    paddingVertical: 15,
    borderRadius: 15,
    backgroundColor: "rgba(255,255,255,0.08)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
    shadowColor: COLORS.shadowColor,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 10,
  },
  statItem: {
    alignItems: "center",
    flex: 1,
  },
  statNumber: {
    color: COLORS.primaryAccent,
    fontSize: 22,
    fontWeight: "bold",
    fontFamily: "Segoe UI Semilight",
  },
  statLabel: {
    color: COLORS.textLightGray,
    fontSize: 12,
    fontFamily: "Segoe UI Semilight",
    marginTop: 4,
  },
  statSeparator: {
    width: 1,
    backgroundColor: "rgba(255,255,255,0.1)",
    height: "80%",
    alignSelf: "center",
  },
  infoBlock: {
    width: "90%",
    backgroundColor: "rgba(255,255,255,0.05)",
    borderRadius: 15,
    padding: 20,
    marginBottom: 25,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
  },
  infoRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 10,
    alignItems: "flex-start",
  },
  infoLabel: {
    color: COLORS.textMediumGray,
    fontSize: 13,
    fontFamily: "Segoe UI Semilight",
    fontWeight: "600",
    marginRight: 10,
    width: "30%",
  },
  infoValue: {
    color: COLORS.textWhite,
    fontSize: 14,
    fontFamily: "Segoe UI Semilight",
    flex: 1,
    textAlign: "right",
  },
  infoValueTitle: {
    color: COLORS.primaryAccent,
    fontSize: 14,
    fontFamily: "Segoe UI Semilight",
    flex: 1,
    textAlign: "right",
  },
  infoValueQuote: {
    color: COLORS.primaryAccent,
    fontSize: 14,
    fontFamily: "Segoe UI Semilight",
    flex: 1,
    textAlign: "right",
    fontStyle: "italic",
  },
  sectionTitle: {
    color: COLORS.primaryAccent,
    fontSize: 16,
    fontWeight: "bold",
    marginBottom: 12,
    marginTop: 15,
    alignSelf: "flex-start",
    fontFamily: "Segoe UI Semilight",
    paddingLeft: 10,
  },
  socialLinksBlock: {
    width: "100%",
    marginBottom: 25,
    paddingHorizontal: 15,
  },
  socialLinksRow: {
    flexDirection: "row",
    justifyContent: "center",
    flexWrap: "wrap",
  },
  socialIconContainer: {
    padding: 10,
    marginHorizontal: 8,
    backgroundColor: "rgba(255,255,255,0.06)",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
  },
  interactiveButtons: {
    flexDirection: "row",
    justifyContent: "space-around",
    width: "90%",
    marginTop: 25,
    paddingTop: 20,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: COLORS.buttonBorder,
  },
  actionButton: {
    backgroundColor: "rgba(255,255,255,0.08)",
    paddingVertical: 12,
    paddingHorizontal: 18,
    borderRadius: 15,
    flex: 1,
    marginHorizontal: 8,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
  },
  actionButtonText: {
    color: COLORS.textWhite,
    fontSize: 14,
    fontWeight: "600",
    fontFamily: "Segoe UI Semilight",
  },
  flipButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.secondaryAccent,
    paddingVertical: 12,
    paddingHorizontal: 25,
    borderRadius: 18,
    marginTop: 25,
    width: "90%",
    shadowColor: COLORS.secondaryAccent,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.5,
    shadowRadius: 15,
    elevation: 10,
  },
  flipButtonText: {
    color: COLORS.cardBackground,
    fontSize: 16,
    fontWeight: "bold",
    fontFamily: "Segoe UI Semilight",
  },
  backFlipButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.secondaryAccent,
    paddingVertical: 12,
    paddingHorizontal: 25,
    borderRadius: 18,
    marginBottom: 25,
    width: "90%",
    shadowColor: COLORS.secondaryAccent,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.5,
    shadowRadius: 15,
    elevation: 10,
  },
  bottomShapeContainer: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: 100,
    overflow: "hidden",
    borderBottomLeftRadius: 25,
    borderBottomRightRadius: 25,
    alignItems: "center",
  },
  bottomShapeMain: {
    position: "absolute",
    bottom: -50,
    width: "120%",
    height: 180,
    borderRadius: 90,
    backgroundColor: COLORS.primaryAccent,
    opacity: 0.2,
  },
  bottomShapeAccent: {
    position: "absolute",
    bottom: -60,
    width: "100%",
    height: 150,
    borderRadius: 75,
    backgroundColor: COLORS.secondaryAccent,
    opacity: 0.1,
    transform: [{ rotate: "-15deg" }],
  },
});